[fnnsgxnexx02@awsva1pllog01 ansible]$ cat backup_ios.yml
---
- name: Capture Cisco Devices backup config output
  hosts: norwalk
  gather_facts: no
  connection: network_cli
  tasks:
    - name: Running show_run command on these cisco devices
      cisco.ios.ios_command:
        commands:
          - show run
      register: show_run_output
      become: yes
      become_method: enable

    - name: ensure backup folder is created
      file:
        path: "/logs/{{ backup_root }}"
        state: directory
        owner: fnnsgxnexx02
        group: priv_network_team
        mode: 0755
      run_once: yes

    - name: ensure device rolder is created
      file:
        path: "/logs/{{ backup_root }}/{{ inventory_hostname }}"
        state: directory
        owner: fnnsgxnexx02
        group: priv_network_team
        mode: 0755

    - name: get timestamp
      command: date +%Y%m%d
      register: timestamp

    - name: Save show run output to file
      copy:
        content: "{{ show_run_output.stdout[0] }}"
        dest: "/logs/{{ backup_root }}/{{ inventory_hostname }}/{{ inventory_hostname }}_{{ timestamp.stdout }}_config_backup.txt"
        owner: fnnsgxnexx02
        group: priv_network_team
        mode: 0644
[fnnsgxnexx02@awsva1pllog01 ansible]$ less hosts.yml
USWV-N9k-BL-SW6 ansible_host=10.245.120.151

[aws_cisco]
aws-apsouth-c8000v-1a ansible_host=10.206.97.11
aws-apsouth-c8000v-1b ansible_host=10.206.97.12
aws-us-east-c8000v-2a ansible_host=10.216.75.5
aws-us-east-c8000v-2b ansible_host=10.216.75.41
#aws-uswest-c8000v-2a ansible_host=192.168.123.67
#aws-uswest-c8000v-2b ansible_host=192.168.123.68

[sdwan]
C000267-017R001P-phman-cedge1 ansible_host=10.51.159.11
C000267-017R002P-phman-cedge2 ansible_host=10.51.159.12
phman4-isr4351-cedge1 ansible_host=10.51.247.11
phman4-isr4351-cedge2 ansible_host=10.51.247.12
usnor-c8300-cedge1 ansible_host=10.51.19.11
usnor-c8300-cedge2 ansible_host=10.51.19.12
usep-c8300-cedge1 ansible_host=10.51.183.11
usep-c8300-cedge2 ansible_host=10.51.183.12
uspla2-c8300-cedge1 ansible_host=10.51.79.11
uspla2-c8300-cedge2 ansible_host=10.51.79.12
usrich-c8300-cedge1 ansible_host=10.51.31.11
usrich-c8300-cedge2 ansible_host=10.51.31.12
inpun-c8300-cedge1 ansible_host=10.51.232.11
inpun-c8300-cedge2 ansible_host=10.51.232.12
usoh1-c8500-cedge1 ansible_host=10.51.87.11
usoh1-c8500-cedge2 ansible_host=10.51.87.12
aws-apsouth-c8000v-1a ansible_host=10.206.97.11
aws-apsouth-c8000v-1b ansible_host=10.206.97.12
aws-us-east-c8000v-2a ansible_host=10.216.75.5
aws-us-east-c8000v-2b ansible_host=10.216.75.41
aws-uswest-c8000v-2a ansible_host=192.168.123.67
aws-uswest-c8000v-2b ansible_host=192.168.123.68

[test]
USWV-N9k-RD-SW1 ansible_host=10.245.120.142

#[wireless]
#uswv-wlc-ap-03 ansible_host=10.41.82.10
#inpun-wlc-01 ansible_host=10.92.232.100
#usep-c9800-wlc01 ansible_host=10.245.178.100
#ric-wlc-01 ansible_host=10.97.24.100
